variables:
  environment: 'demo'
  action: 'apply'
  application: 'argocd'
  landingzone_key : 'cluster_aks'
  cluster_key: 'cluster_re1'
  base_uri: ''

#####################################################################
# APP Deployment
#####################################################################

stages:
  - aks
  - argocd

aks:
  stage: aks
  tags:
    - gitlab-runner-3
  script:
    - |
      git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@${base_uri}/${CI_PROJECT_NAMESPACE}/caf_modules.git

      az login --identity --username ${MSI_ID_03}

      /tf/rover/rover.sh -lz ${CI_PROJECT_DIR}/caf_modules/landingzones/caf_solution \
      -tfstate landing_zone_aks.tfstate \
      -var-folder ${CI_PROJECT_DIR}/level3/aks \
      -parallelism 30 \
      -level level3 \
      -env ${environment} \
      -a ${action}

argocd:
  stage: argocd
  tags:
    - gitlab-runner-4
  script:
    - |
      az login --identity --username ${MSI_ID_04}

      /tf/rover/rover.sh -lz ${CI_PROJECT_DIR}/custom_modules/landingzones/aks_applications \
      -tfstate ${application}1.tfstate \
      -var-folder ${CI_PROJECT_DIR}/level4/argocd \
      -var tags={application=\"${application}\"} \
      -level level4 \
      -env ${environment} \
      -a ${action}
