#cloud-config
package_upgrade: true

packages:
    - docker.io
    - docker-compose

groups:
    - docker

users:
    - default
    - name: gitlab
      groups: docker


# package_update: true

# packages:
#   - apt-transport-https
#   - ca-certificates
#   - curl
#   - gnupg-agent
#   - software-properties-common

# runcmd:
#   - echo "here" > /tmp/message.txt
#   - whoami > /tmp/symphony.init.log
#   - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
#   - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
#   - apt-get update -y
#   - apt-get install docker-ce docker-ce-cli containerd.io
#   - systemctl start docker
#   - systemctl enable docker

# system_info:
#     default_user:
#         groups: [docker]  